# Default values for Directus Helm Chart

replicaCount: 1

image:
  repository: directus/directus
  tag: "11.1"
  pullPolicy: Always

envFrom:
  configMapRef:
    name: directus-configuration
  secretRef:
    name: directus-secret
  configMapObjectStorageRef:
    name: directus-object-storage-configuration
  configMapDatabaseRef:
    name: directus-database-configuration

service:
  port: 8055

resources:
  requests:
    memory: "256Mi"
    cpu: "250m"
  limits:
    memory: "512Mi"
    cpu: "500m"
