apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-directus
  labels:
    app: {{ .Release.Name }}-directus
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-directus
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-directus
    spec:
      containers:
        - name: directus
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default "latest" }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
          envFrom:
            - configMapRef:
                name: {{ default "directus-configuration" }}
            - secretRef:
                name: {{ default "directus-secret" }}
          ports:
            - containerPort: {{ .Values.service.port | default 8055 }}
              protocol: TCP
          resources:
            requests:
              memory: {{ .Values.resources.requests.memory | default "256Mi" }}
              cpu: {{ .Values.resources.requests.cpu | default "250m" }}
            limits:
              memory: {{ .Values.resources.limits.memory | default "512Mi" }}
              cpu: {{ .Values.resources.limits.cpu | default "500m" }}
