apiVersion: v1
kind: Secret
metadata:
  name: directus-secret
type: Opaque
stringData:
  ADMIN_EMAIL: {{ .Values.adminEmail | default "example@mayday.xyz" }}
  ADMIN_PASSWORD: {{ default (randAlphaNum 16) }} 
  KEY: {{ default (randAlphaNum 32) }} 
  SECRET: {{ default (randAlphaNum 32) }} 
  STORAGE_S3_SECRET: {{ default (randAlphaNum 16) }}
  DB_PASSWORD: {{ default (randAlphaNum 16) }} 
